Repository team-unchained/grantly, pull requests merged in 2025-07, with the labels that each got.

#127 admin path prefix 추가 및 UserDetails 구현체에 role 추가
  src/api/src/main/kotlin/grantly/app/adapter/in/AppClientController.kt
  src/api/src/main/kotlin/grantly/app/adapter/in/AppController.kt
  src/api/src/main/kotlin/grantly/config/AuthenticationEntity.kt
  src/api/src/main/kotlin/grantly/config/SecurityConfig.kt
  src/api/src/main/kotlin/grantly/config/filter/SessionValidationFilter.kt
  src/api/src/main/kotlin/grantly/member/adapter/in/MemberAuthController.kt
  src/api/src/main/kotlin/grantly/member/adapter/in/MemberController.kt
  src/api/src/main/kotlin/grantly/member/application/service/MemberService.kt
  src/api/src/main/kotlin/grantly/session/domain/AuthSessionDomain.kt
  src/api/src/main/kotlin/grantly/system/adapter/in/SystemController.kt
  src/api/src/test/kotlin/grantly/app/adapter/in/AppClientControllerTest.kt
  src/api/src/test/kotlin/grantly/app/adapter/in/AppControllerTest.kt
  src/api/src/test/kotlin/grantly/config/WithMemberSessionSecurityContextFactory.kt
  src/api/src/test/kotlin/grantly/config/WithTestSessionMember.kt
  src/api/src/test/kotlin/grantly/member/adapter/in/AuthControllerTest.kt
  src/api/src/test/kotlin/grantly/member/adapter/in/MemberControllerTest.kt
Labels: BE

#128 null인 이미지 경로 반환되는 현상 수정
  src/api/src/main/kotlin/grantly/app/adapter/in/AppController.kt
  src/api/src/main/kotlin/grantly/app/domain/AppDomain.kt
Labels: bug, BE

#131 [FE] 멤버 전용 api 에 /admin prefix 추가
  src/frontend/src/api/app/appApi.ts
  src/frontend/src/api/auth/authApi.ts
  src/frontend/src/api/oauth/oauthApi.ts
  src/frontend/src/api/user/userApi.ts
Labels: FE, fix

#130 DB 테이블 이름을 단수로 통일함
  src/api/src/main/kotlin/grantly/app/adapter/out/AppClientJpaEntity.kt
  src/api/src/main/resources/migrations/V11__alter_table_name_singualr.sql
  src/api/src/main/resources/migrations/V8__create_app_clients_table.sql
  src/api/src/test/resources/schema-h2.sql
Labels: BE, DB migration

#133 회원가입시 app 생성 해주던 로직 제거
  src/api/src/main/kotlin/grantly/member/application/service/MemberService.kt
  src/api/src/test/kotlin/grantly/member/adapter/in/AuthControllerTest.kt
Labels: BE
