Repository team-unchained/grantly, pull requests merged in 2025-06, with the labels that each got.

#99 deploy workflow 에 tailscale 추가
  .github/workflows/reusable-deploy.yml
Labels: infra

#107 refac: service to app
  src/frontend/src/api/app/app.shcema.ts
  src/frontend/src/api/app/appApi.ts
  src/frontend/src/api/app/appMock.ts
  src/frontend/src/api/app/queryKey.ts
  src/frontend/src/api/app/useAppQueries.ts
  src/frontend/src/api/service/queryKey.ts
  src/frontend/src/api/service/serviceApi.ts
  src/frontend/src/api/service/useServiceQueries.ts
  src/frontend/src/components/dashboard/sidebar/AppSwitcher.tsx
  src/frontend/src/components/dashboard/sidebar/DashBoardSideBar.tsx
  src/frontend/src/constants/DashboardMenu.ts
  src/frontend/src/hooks/contexts/AuthProvider.tsx
Labels: refac

#111 회원가입 시 기본 애플리케이션 생성
  src/api/src/main/kotlin/grantly/app/adapter/in/AppController.kt
  src/api/src/main/kotlin/grantly/app/adapter/out/AppJpaRepository.kt
  src/api/src/main/kotlin/grantly/app/adapter/out/AppPersistenceAdapter.kt
  src/api/src/main/kotlin/grantly/app/application/port/out/AppRepository.kt
  src/api/src/main/kotlin/grantly/app/application/service/AppService.kt
  src/api/src/main/kotlin/grantly/app/application/service/exceptions/CannotDeleteLastActiveAppException.kt
  src/api/src/main/kotlin/grantly/member/application/service/MemberService.kt
  src/api/src/test/kotlin/grantly/app/adapter/in/AppControllerTest.kt
  src/api/src/test/kotlin/grantly/member/adapter/in/AuthControllerTest.kt
  src/api/src/test/kotlin/grantly/member/adapter/in/MemberControllerTest.kt
Labels: BE
