Repository team-unchained/grantly, pull requests merged in 2025-03, with the labels that each got.

#19 User 엔티티 재작성
  src/api/src/main/kotlin/grantly/user/adapter/out/UserJpaEntity.kt
  src/api/src/main/kotlin/grantly/user/adapter/out/UserMapper.kt
  src/api/src/main/kotlin/grantly/user/domain/User.kt
  src/api/src/main/resources/application.yml
  src/api/src/main/resources/migrations/V1__add_user_table.sql
Labels: BE, DB migration

#14 front init
  .yarnrc.yml
  package.json
  src/frontend/.eslintignore
  src/frontend/.eslintrc.json
  src/frontend/.gitignore
  src/frontend/.prettierrc
  src/frontend/next.config.ts
  src/frontend/package.json
  src/frontend/postcss.config.mjs
  src/frontend/public/file.svg
  src/frontend/public/globe.svg
  src/frontend/public/next.svg
  src/frontend/public/vercel.svg
  src/frontend/public/window.svg
  src/frontend/src/app/favicon.ico
  src/frontend/src/app/globals.css
  src/frontend/src/app/layout.tsx
  src/frontend/src/app/page.tsx
  src/frontend/tsconfig.json
  yarn.lock
Labels: ASAP, FE

#38 CORS 설정 추가
  src/api/src/main/kotlin/grantly/config/SecurityConfig.kt
Labels: BE

#37 sign Up Api 연결 및 UI
  src/frontend/package.json
  src/frontend/src/api/auth/auth.schema.ts
  src/frontend/src/api/auth/authApi.ts
  src/frontend/src/api/auth/useAuthQueries.ts
  src/frontend/src/api/axiosInstance.ts
  src/frontend/src/app/layout.tsx
  src/frontend/src/app/providers.tsx
  src/frontend/src/app/welcome/page.tsx
  src/frontend/src/components/common/FormInputField.tsx
  src/frontend/src/components/sign-up/SignUpFormCard.tsx
  src/frontend/src/components/ui/sonner.tsx
  src/frontend/src/types/user.d.ts
  yarn.lock
Labels: feature, FE
